// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://motvmoeclapwifvkowlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vdHZtb2VjbGFwd2lmdmtvd2xtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0ODA0MTcsImV4cCI6MjA3NzA1NjQxN30.xl5W8UPV-rjXAfizJ7To-6TQ6VE2xk40MBpY34r80OY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
